services:
  salary_front:
    image: node:22.3.0-alpine
    container_name: salary_front
    restart: always
      #command: sh -c "cd /code && npm install && npm run build && npm start"
    command: sh -c "cd /code && npm install && npm run dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=dev
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - .:/code

networks:
  default:
    external:
      name: airoldi_docker
